<?php /** @var $block \Smile\Blog\Block\CategoryList */ ?>
<h1><?php echo __('Blog Posts') ?></h1>
<ul class="blog-post-list">
    <?php /** @var $post \Smile\Blog\Model\Post */?>
    <?php foreach ($block->getPosts() as $post): ?>
        <li class="blog-post-list-item">
            <h3 class="blog-post-item-title">
                <a href="/m2/blog/post?id=<?=$post->getId()?>"><?php echo $post->getTitle() ?></a>
            </h3>
            <div class="blog-cpost-item-image">
                <img src="/m2/pub/media/<?= $post->getImage() ?>" alt="" />
            </div>
            <div class="blog-post-item-description">
                <?php echo $post->getDescription(); ?>
            </div>
            <div class="blog-post-item-meta">
                <strong><?php echo __('Created at:') ?></strong> <?php echo $post->getCreated() ?><br/>
            </div>
        </li>
    <?php endforeach; ?>
</ul>