<img src="http://local.dev/m2/pub/media/catalog/product/cache/f073062f50e48eb0f0998593e568d857/m/j/mj09-yellow_main.jpg" alt="Taurus Elements Shell" style="float: left; padding-right: 50px">

<?php echo $block->getProductDescription().'<br>';?>

<div style="color: #4a8d94; padding-top: 15px; font-size: 35px"><?= $block->getProductPrice();?></div><br>

<button type="submit" title="Add to Cart" class="action primary tocart" id="product-addtocart-button">
    <span>Add to Cart</span>
</button>
