<h1><?= $block->getSaleMassage();?><h1>

<a href="http://local.dev/m2/promotions/women-sale.html" class="block-promo sale-main">
    <img src="http://local.dev/m2/pub/media/wysiwyg/sale/sale-main.jpg" alt="">
    <span class="content">
        <span class="info">Women’s Deals</span>
        <strong class="title">Pristine prices on pants, tanks and bras.</strong>
        <span class="more button">Shop Women’s Deals</span>
    </span>
</a>